version: '3.8'

services:
  # Frontend Service
  frontend:
    build:
      context: ./client   # Path to your frontend directory
      dockerfile: Dockerfile # Dockerfile for frontend
    ports:
      - "5173:5173"          # Expose frontend on port 5073
    env_file:
      - ./client/.env.sample
    depends_on:
      - backend              # Ensure backend is running
    networks:
      - app-network

  # Backend Service
  backend:
    build:
      context: ./server     # Path to your backend directory
      dockerfile: Dockerfile # Dockerfile for backend
    ports:
      - "5014:5014"          # Expose backend on port 4000
    env_file:
      - ./server/.env.sample
    depends_on:
      - db                  # Ensure database is running
    networks:
      - app-network

  # MongoDB Database Service
  db:
    image: mongo:latest      # Use the latest MongoDB image
    container_name: mongo_db
    ports:
      - "27017:27017"        # Expose MongoDB on port 27017
    volumes:
      - ./server/data:/data  # Persist MongoDB data
    networks:
      - app-network

# Volumes for database persistence
volumes:
  data:

# Networks to connect services
networks:
  app-network:
    driver: bridge
