version: "3.8"

services:
  mongodb:
    container_name: mongo
    image: mongo:latest
    volumes:
      - ./backend/data:/data/db  # Ensure you're pointing to the correct MongoDB data directory
    ports:
      - "27017:27017"

  backend:
    container_name: backend
    build: ./backend
    env_file:
      - ./backend/.env.sample
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app  # Mount the backend directory for live changes

  frontend:
    container_name: client
    build: ./client
    env_file:
      - ./client/.env.sample
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app  # Mount the frontend directory for live changes
      
volumes:
  data:
